#!/usr/bin/env python

from glob import glob
from pathlib import Path

import methods

Import("env")

env.platform_sources = []


# Generate export icons
def export_icon_builder(target, source, env):
    src_path = Path(str(source[0]))
    src_name = src_path.stem
    platform = src_path.parent.parent.stem
    with open(str(source[0]), "rb") as file:
        svg = "".join([f"\\{hex(x)[1:]}" for x in file.read()])
    with methods.generated_wrapper(target, prefix=platform) as file:
        file.write(
            f"""\
static const char *_{platform}_{src_name}_svg = "{svg}";
"""
        )


for platform in env.platform_exporters:
    for path in glob(f"{platform}/export/*.svg"):
        env.CommandNoCache(path.replace(".svg", "_svg.gen.h"), path, env.Run(export_icon_builder))

env.add_source_files(env.platform_sources, "*.cpp")

lib = env.add_shared_library("platform", env.platform_sources)
env.Prepend(LIBS=[lib])
